[package]
name = "headlessui-sycamore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = { path = "../sycamore/packages/sycamore" }
sycamore-utils = { path = "../sycamore-utils" }
web-sys = { version = "0.3", features = ["KeyboardEvent", "HtmlElement", "Selection"] }
fluvio-wasm-timer = "0.2"
wasm-bindgen-futures = "0.4"