[dependencies]
console_error_panic_hook = "0.1"
log = "0.4"
wasm-logger = "*"

[dependencies.headlessui-sycamore]
path = "../.."

[dependencies.sycamore]
git = "https://github.com/sycamore-rs/sycamore.git"

[package]
edition = "2021"
name = "example-radio-group"
version = "0.1.0"
