[dependencies]
console_error_panic_hook = "0.1"
wasm-logger = "0.2"

[dependencies.headlessui-sycamore]
path = "../.."

[dependencies.sycamore]
git = "https://github.com/sycamore-rs/sycamore.git"

[package]
edition = "2021"
name = "example-menu"
version = "0.1.0"
